### ISSUE TITLE
Cannot import espressomd on armhf build

### ISSUE THREAD

**Issue by jngrad** [espressomd/docker#108]
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/127772
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/127809
```
3/3 Test #3: test_python_bindings .............***Failed    5.64 sec
Python xx
    non-zero return code (1) for command `/builds/espressomd/docker/espresso/build/pypresso -c import sys;sys.path.insert(0, '/builds/espressomd/docker/espresso/build/testsuite/cmake/install//tmp/espresso-unit-tests/lib/python3/dist-packages');import espressomd`
```
The full message also mentions `opal_init`, `opal_shmem_base_select`, `orte_init`, `MPI_INIT`, `ompi_mpi_init`, `ompi_rte_init`.

**Comment by jngrad** [comment]
This issue occurred on bwCloud and elk. I couldn't reproduce it on coyote2 nor on my desktop machine.

**Comment by KaiSzuttor** [comment]
I think we should go back to use docker-in-docker again...

**Comment by mkuron** [comment]
Why do you think this would be fixed by docker-in-docker? All the other tests passed, so it is more likely an OpenMPI thing.

**Comment by KaiSzuttor** [comment]
its a more general comment on how we should build the images. the kaniko/bwcloud stuff introduced quite some headache

**Comment by jngrad** [comment]
Statistics: armhf never failed on coyotes
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/127168
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/127320
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/127674
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/127435
We could add an `icp` label to the `test/ubuntu:armhf` for now.

**Comment by mkuron** [comment]
Hmm, kernel version maybe? Or the CPU? elk is running Ubuntu 16.04 on a very old CPU, while bwCloud uses Debian inside KVM virtualization on a relatively new CPU. The coyotes and @jngrad's computer are running Ubuntu 18.04 and are somewhere in between in terms of CPU.

Once the new build machines are here, I think we'll switch off bwCloud again. It just has too much overhead (see the wiki article) to run efficiently and still has that odd issue where sometimes the QEMU emulation doesn't work (which I've never been able to reproduce).

**Comment by jngrad** [comment]
The new `icp` tag in 62051b3 doesn't really help, the container may still end up being tested on elk:
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/128553

**Comment by jngrad** [comment]
This problem hasn't re-occurred in a while. bwCloud machines aren't used anymore. Closing.
