### ISSUE TITLE
Error 137

### ISSUE THREAD

**Issue by jngrad** [espressomd/docker#109]
Multiple jobs on coyote ended prematurely today with error code 137:
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/128229
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/128230
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/128495
This code is probably a SIGKILL (128 + 9 = 137).

**Comment by KaiSzuttor** [comment]
this looks like a reboot of the runner

**Comment by KaiSzuttor** [comment]
havent seen it since then
