### ISSUE TITLE
Bug: Docker Container

### ISSUE THREAD

**Issue by carlos-pereyra** [espressomd/docker#142]
I am having issues installing pypresso on Mac OS X.

I decided to use the docker container `clang-python3` and cloned the espressomd repo, once inside the container.

I then did the following

`mkdir build`

`cd build`

`cmake ..`

`make -j8`

`make install`

But during the install I get the following error.

> Install the project...
-- Install configuration: "Release"
CMake Error at src/core/cmake_install.cmake:42 (file):
  file cannot create directory:
  /usr/local/lib/python3/dist-packages/espressomd.  Maybe need administrative
  privileges.
Call Stack (most recent call first):
  src/cmake_install.cmake:37 (include)
  cmake_install.cmake:39 (include)

Makefile:85: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by KaiSzuttor** [comment]
this is actually not a bug... the docker image is by default run with the ```espresso``` user which does not have root permissions. Either you don't install, or you have to provide a different directory for installation via ```cmake -DCMAKE_INSTALL_PREFIX=/tmp/espresso```

**Comment by carlos-pereyra** [comment]
Ahh thanks!
