### ISSUE TITLE
dockerhub deploy not working

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/docker#168]
``` bash
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

**Comment by jngrad** [comment]
When I do it manually, docker uses by default `https://index.docker.io/v1/`. Workflow:
```sh
# login and push the image
docker login
docker push espressomd/espresso-ubuntu-python3:latest
docker logout
```
Output:
```
The push refers to repository [docker.io/espressomd/espresso-ubuntu-python3]
820db5dc53c2: Pushed
4abb9d100732: Pushed
...
```

**Comment by KaiSzuttor** [comment]
are you sure that you used the token and the username stored as a secret?

**Comment by jngrad** [comment]
I tested it and immediately copy-pasted it in the espressomd/docker Settings. I can't try the token again because it's only visible once on DockerHub and not recoverable from GitHub, I and didn't store it elsewhere. According to DockerHub, the token wasn't used by GitHub:
```
Created:  Apr 03, 2020   11:14:34
Last use: Apr 03, 2020   11:17:34
```

**Comment by KaiSzuttor** [comment]
just create a new token and overwrite the secret on github

**Comment by jngrad** [comment]
done

**Comment by KaiSzuttor** [comment]
new error
``` bash
Error response from daemon: Get https://docker.pkg.github.com/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by jngrad** [comment]
Actually, the images get deployed to DockerHub. Could it be that the docker command that logs into the DockerHub registry with the secret token is overwriting the `auth` for the GitHub registry, preventing the logout?
