### ISSUE TITLE
some Dockerfiles don't build

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/docker#48]
rocm - due to missing branch in @mkuron s github repository
arm64 - due to some dpkg error

**Comment by KaiSzuttor** [comment]
@mkuron

**Comment by KaiSzuttor** [comment]
rocm build hangs...

https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/54944

**Comment by mkuron** [comment]
Please close this issue
