### ISSUE TITLE
ccache on centos is broken

### ISSUE THREAD

**Issue by fweik** [espressomd/docker#57]
cf. https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/66484:
```
[  1%] Building CXX object src/config/CMakeFiles/EspressoConfig.dir/config-features.cpp.o
ccache: error: Failed to create temporary file for /cache/tmp/tmp.cpp_stderr: Permission denied
make[2]: *** [src/config/CMakeFiles/EspressoConfig.dir/config-features.cpp.o] Error 1
```
could be a side effect of #56 ?

**Comment by KaiSzuttor** [comment]
why dont we change the permissions?

**Comment by mkuron** [comment]
That's not sufficient. ccache creates new files and directories owned by the user it is run as. So if they are expired/cleaned up by a ccache running under a different UID, you have a problem. You could of course mess with the umask, but that might end up giving write access to the cache to anyone who can SSH into the build machine (which they could abuse to inject stuff into the cache). So the safest and easiest way is to have ccache running as the same UID everywhere.

**Comment by fweik** [comment]
You can set the uid in the docker file like this:
```
USER espressomd:5000
```
(https://docs.docker.com/engine/reference/builder/#user)

**Comment by mkuron** [comment]
I don't think you can set both the name and the UID. The documentation say `USER <user>[:<group>]` or `USER <UID>[:<GID>]`.

**Comment by fweik** [comment]
Hmhm
