### ISSUE TITLE
Container inheritance

### ISSUE THREAD

**Issue by jngrad** [espressomd/docker#64]
Does our infrastructure currently allow containers deriving from one another? The goal would be to build container `cuda:8` from `docker/cuda/Dockerfile-8.0`, then build `cuda:8-tutorial` from `docker/cuda/Dockerfile-8.0-tutorial` where the first line would be `FROM cuda:8`. This way the second Dockerfile doesn't need to contain a full copy of the base Dockerfile, hence reducing the maintenance effort.

**Comment by mkuron** [comment]
You can already do `FROM gitlab.icp.uni-stuttgart.de:4567/docker/cuda:8.0`. However, if you update the base image, the derived image will only pick it up during the next build cycle.
