### ISSUE TITLE
Test stage cannot pull images from build stage

### ISSUE THREAD

**Issue by jngrad** [espressomd/docker#92]
Happens at random. Retrying doesn't help, the entire pipeline must be restarted. When this happens after merging a PR, the inaccessible images can nevertheless be downloaded from outside, e.g. from runners in the espressomd/espresso CI or from a desktop machine.
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/117339
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/118204

**Comment by mkuron** [comment]
Did you try `docker run -it gitlab.icp.uni-stuttgart.de:4567/espressomd/docker/test/ubuntu-python3:18.04-62a2bc70d764a94c6acbad6be862d363c6335827 /bin/bash`? No error there? That‘s going to be difficult to diagnose. Silent image corruption inside the Docker registry maybe? Bad caching?

**Comment by jngrad** [comment]
Just tried out your docker cmd and it worked. While we diagnose the issue, do you have a method to retry an entire pipeline? When hitting the `Retry` button on this [pipeline](https://gitlab.icp.uni-stuttgart.de/espressomd/docker/pipelines/7452), it only retries the failed/canceled jobs.

**Comment by mkuron** [comment]
Go to https://gitlab.icp.uni-stuttgart.de/espressomd/docker/pipelines/new and select the pull request‘s branch.

**Comment by mkuron** [comment]
https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/118345 has an interesting error:

> error building image: error building stage: extracting fs from image: link /usr/share/perl5/unicore/lib/Bc /usr/lib64/python3.7/distutils/\_\_pycache\_\_/dir_util.cpython-37.opt-1.pyc: operation not permitted

No idea what that means, but it looks like a corrupted image.

**Comment by jngrad** [comment]
I've retried the pipeline again, still the same error message. The Dockerfile is correct though, because it was built successfully in the first pipeline. If we compare both logfiles:
* [first build](https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/118004)
 ```
 INFO[0007] Checking for cached layer gitlab.icp.uni-stuttgart.de:4567/espressomd/docker
 /cache:f2227765e1c8edc9564a57d37f12f3d1613f3ad3c632bcdf3e629161784a9b34... 
 INFO[0008] No cached layer found for cmd RUN yum -y install gcc gcc-c++ make cmake...
 ```
* [next build](https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/118345)
 ```
 INFO[0004] Checking for cached layer gitlab.icp.uni-stuttgart.de:4567/espressomd/docker/
 cache:f2227765e1c8edc9564a57d37f12f3d1613f3ad3c632bcdf3e629161784a9b34... 
 INFO[0004] Using caching version of cmd: RUN yum -y install gcc gcc-c++ make cmake...
 ```
We could try deleting the `cache:f22277...` layer and rebuild the image.

**Comment by jngrad** [comment]
Deleting the faulty layer fixed the issue.

**Comment by mkuron** [comment]
It's back here: https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/118579

And when I `docker pull gitlab.icp.uni-stuttgart.de:4567/espressomd/docker/ubuntu:arm64`, I now get a proper error message:

> failed to register layer: Error processing tar file(exit status 1): link /usr/share/icons/ubuntu-mono-dark/apps/24 /usr/lib/python3.7/lib2to3/fixes/fix_except.py: operation not permitted

That looks like a corrupted tarball as it makes no sense to link a directory of icons to a python script. Attaching strace to the dockerd process while the extraction is running:
> unlinkat(AT_FDCWD, "/scratch/docker/overlay2/XXX/diff/usr/share/icons/ubuntu-mono-dark/apps/24", 0) = -1 EISDIR (Is a directory)
unlinkat(AT_FDCWD, "/scratch/docker/overlay2/XXX/diff/usr/share/icons/ubuntu-mono-dark/apps/24", AT_REMOVEDIR) = -1 ENOTEMPTY (Directory not empty)
lstat("/scratch/docker/overlay2/XXX/diff/usr/share/icons/ubuntu-mono-dark/apps/24", {st_mode=S_IFDIR|0755, st_size=112, ...}) = 0
openat(AT_FDCWD, "/scratch/docker/overlay2/XXX/diff/usr/share/icons/ubuntu-mono-dark/apps/24", O_RDONLY|O_CLOEXEC) = 31
unlinkat(AT_FDCWD, "/scratch/docker/overlay2/XXX/diff/usr/share/icons/ubuntu-mono-dark/apps/24/audacious-panel.svg", 0) = 0
unlinkat(AT_FDCWD, "/scratch/docker/overlay2/XXX/diff/usr/share/icons/ubuntu-mono-dark/apps/24/gnome-do-symbolic.svg", 0) = 0
unlinkat(AT_FDCWD, "/scratch/docker/overlay2/XXX/diff/usr/share/icons/ubuntu-mono-dark/apps/24/transmission-tray-icon.svg", 0) = 0
unlinkat(AT_FDCWD, "/scratch/docker/overlay2/XXX/diff/usr/share/icons/ubuntu-mono-dark/apps/24", 0) = -1 EISDIR (Is a directory)
unlinkat(AT_FDCWD, "/scratch/docker/overlay2/XXX/diff/usr/share/icons/ubuntu-mono-dark/apps/24", AT_REMOVEDIR) = 0
lstat("/usr/lib/python3.7/lib2to3/fixes/fix_except.py", 0xc420cba928) = -1 ENOENT (No such file or directory)
linkat(AT_FDCWD, "/usr/share/icons/ubuntu-mono-dark/apps/24", AT_FDCWD, "/usr/lib/python3.7/lib2to3/fixes/fix_except.py", 0 <unfinished ...>

Why would it attempt to put something in a path outside /scratch/docker?

Even more odd observation: this image was built in https://gitlab.icp.uni-stuttgart.de/espressomd/docker/-/jobs/118421. `docker pull gitlab.icp.uni-stuttgart.de:4567/espressomd/docker/ubuntu:arm64` fails with the above error, while `docker pull gitlab.icp.uni-stuttgart.de:4567/espressomd/test/ubuntu:arm64-8ca8df0493fce9c04c3f589764e31b41cfa76c5c` succeeds -- but both images should actually be the same.

Maybe we should try disabling caching in https://github.com/espressomd/docker/blob/master/maintainer/docker_build.sh#L21 for now...

**Comment by KaiSzuttor** [comment]
HDD issues?

**Comment by mkuron** [comment]
No, it's independent of the runner, while the registry runs on a RAID. It looks like a bug somewhere -- Docker registry, Docker build process, Docker extraction process, ...
